"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:surface0)\
$directory\
[](fg:surface0 bg:green)\
$git_branch\
$git_status\
[](fg:green)\
$line_break$character
"""

palette = 'kanagawa'

[palettes.kanagawa]
text     = "#DCD7BA"
mantle   = "#0F1419"
surface0 = "#1F1F28"
green    = "#98BB6C"
teal     = "#7AA89F"
red      = "#C34043"
blue     = "#7FB4CA"
accent1  = "#DCA561"
accent2  = "#7E9CD8"

[directory]
style             = "fg:text bg:surface0"
format            = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
symbol = ""
style  = "bg:green"
format = '[[ $symbol $branch ](fg:mantle bg:green)]($style)'

[git_status]
style  = "bg:green"
format = '[[$all_status$ahead_behind ](fg:mantle bg:green)]($style)'

[c]
format = ''

[rust]
format = ''

[golang]
format = ''

[python]
format = ''

[docker_context]
format = ''

[line_break]
disabled = false

[character]
success_symbol = '[❯](bold fg:green)'
error_symbol   = '[❯](bold fg:red)'
