"$schema" = 'https://starship.rs/config-schema.json'
format = """
[](fg:surface0)\
$directory\
[](fg:surface0 bg:green)\
$git_branch\
$git_status\
[](fg:green)\
$line_break$character
"""
palette = 'everforest'

[palettes.everforest]
text     = "#D3C6AA"
mantle   = "#1E2326"
surface0 = "#272E33"
green    = "#A7C080"
teal     = "#83C092"
red      = "#E67E80"
blue     = "#7FBBB3"
accent1  = "#E69875"
accent2  = "#DBBC7F"

[directory]
style             = "fg:text bg:surface0"
format            = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
symbol = ""
style  = "bg:green"
format = '[[ $symbol $branch ](fg:mantle bg:green)]($style)'

[git_status]
style  = "bg:green"
format = '[[$all_status$ahead_behind ](fg:mantle bg:green)]($style)'

[c]
format = ''
[rust]
format = ''
[golang]
format = ''
[python]
format = ''
[docker_context]
format = ''
[line_break]
disabled = false

[character]
success_symbol = '[❯](bold fg:green)'
error_symbol   = '[❯](bold fg:red)'
