"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](bg:mantle fg:surface0)\
$directory\
[](fg:surface0 bg:green)\
$git_branch\
$git_status\
[](fg:green bg:teal)\
$c\
$rust\
$golang\
$python\
[](fg:teal)\
$line_break$character
"""

palette = 'kanagawa'

[palettes.kanagawa]
text     = "#DCD7BA"
mantle   = "#0F1419"
surface0 = "#1F1F28"
green    = "#98BB6C"
teal     = "#7AA89F"
red      = "#C34043"
blue     = "#7FB4CA"
accent1  = "#DCA561"
accent2  = "#7E9CD8"

[directory]
style            = "fg:mantle bg:surface0"
format           = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:mantle bg:green)]($style)'

[git_status]
style = "bg:green"
format = '[[ $all_status$ahead_behind ](fg:mantle bg:green)]($style)'

[c]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:mantle bg:teal)]($style)'

[rust]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:mantle bg:teal)]($style)'

[golang]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:mantle bg:teal)]($style)'

[python]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:mantle bg:teal)]($style)'

[docker_context]
symbol = ""
style = "bg:blue"
format = '[[ $symbol $context ](fg:mantle bg:blue)]($style)'
only_with_files = true

[time]
time_format = "%R"
style = "bg:accent2"
format = '[[  $time ](fg:mantle bg:accent2)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
