# Max gamma limit
max-gamma = 150

# Daytime — neutral color temperature
profile {
    time = 07:30
    temperature = 6500
    gamma = 1.0
}

# Night — warm temperature
profile {
    time = 21:00
    temperature = 4000
    gamma = 0.9
}
