hl.on("hyprland.start", function()
    hl.exec_cmd("foot --server")
    hl.exec_cmd("waybar")
    hl.exec_cmd("systemctl --user start hypridle.service")
    hl.exec_cmd("systemctl --user start hyprsunset.service")
    hl.exec_cmd("systemctl --user start polkit-gnome-authentication-agent-1")
    hl.exec_cmd("wl-paste --type text --watch cliphist --max-items 12 store")
    hl.exec_cmd("wl-paste --type image --watch cliphist --max-items 10 store")
    hl.exec_cmd("~/.config/hypr/scripts/random-wallpaper")
end)
