exec-once = hyprsunset
exec-once = waybar
exec-once = systemctl --user start polkit-gnome-authentication-agent-1
exec-once = wl-paste --type text --watch cliphist --max-items 12 store
exec-once = wl-paste --type image --watch cliphist --max-items 10 store
exec-once = swww-daemon
exec-once = timeout 5 bash -c 'while [ ! -S /tmp/swww.socket ]; do sleep 0.1; done; ~/.config/hypr/scripts/random-wallpaper'
exec-once = ~/.config/hypr/scripts/idle
